In [1]:
help(len)

Help on built-in function len in module builtins:

len(obj, /)
    Return the number of items in a container.



In [2]:
len?

In [3]:
import numpy as np
np.array?

In [4]:
def square(a):
    """Return square a"""
    return a ** 2

In [5]:
square?

In [6]:
np?

In [7]:
np.doc?

Object `np.doc` not found.


In [8]:
np.array([1, 2, 3, 4], dtype='float32')

array([1., 2., 3., 4.], dtype=float32)

In [9]:
# Создаем массив целых чисел длины 10, заполненной нулями.
np.zeros(10, dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [10]:
np.zeros((2, 2), dtype=int)

array([[0, 0],
       [0, 0]])

In [11]:
# Создаем массив размером 3 х 5 значений с плавающей точкой, заполненный единицами
np.ones((3, 5), dtype=float)

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [12]:
# Создаем массив размером 2 х 6 заполненный р
np.full((2, 4), 3.14)

array([[3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14]])

In [13]:
# Создаем массив заполненный линейной последовательностью, начинающийся с 0 и заканчивающийся 20 с шагом 2
# (Аналогично встроенной функции range())
np.arange(0, 20, 2, dtype=float)

array([ 0.,  2.,  4.,  6.,  8., 10., 12., 14., 16., 18.])

In [14]:
np.arange?

In [15]:
# Создаем массив из 5 значений, равномерно располагающихся между 0 и 1
np.linspace(0, 1, 5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [16]:
# Создаем массив размером 3 х 3 равномерно распределенных случайных значений от 0 до 1
np.random.random((3, 3))

array([[0.46823874, 0.70793891, 0.78791491],
       [0.32756338, 0.435256  , 0.3096526 ],
       [0.06060456, 0.10134928, 0.49975305]])

In [17]:
# Создаем массив размером 4 х 4 нормально распределенных случайных значений,
# с медианой 0 и стандартным отклонением 1
np.random.normal(0, 1, (4, 4))

array([[-0.68691859, -1.95725133, -0.45395519,  0.1437085 ],
       [-0.49599805,  1.83636456,  0.3169035 ,  0.11449584],
       [-1.40544061,  1.61891799, -1.35546598, -0.97034117],
       [-0.18916587,  0.0285938 , -0.36813526, -1.16765258]])

In [18]:
# Создаем массив размером 3 х 3 случайных целых чисел в промежутке [0, 10)
np.random.randint(0, 10, (3, 3))

array([[5, 0, 8],
       [7, 0, 3],
       [5, 5, 3]])

In [19]:
# Создаем единичную матрицу 3 х 3
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [20]:
# Можно принудительно привести к типу С
np.zeros(10, dtype=np.int16)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int16)

In [21]:
# Воспользуемся генератором случайных чисел библиотеки numpy, задав для него начальное значение,
# чтобы гарантировать генерацию одних и тех же массивов при каждом выполнении кода:

np.random.seed(0) # начальное значение для целей воспроизводимости

x1 = np.random.randint(10, size=6) # одномерный массив
x2 = np.random.randint(10, size=(3, 4)) # двумерный массив
x3 = np.random.randint(10, size=(3, 4, 5)) # трехмерный массив

In [22]:
# У каждого из массивов есть атрибуты ndim (размерность), shape (размер каждого измерения) и size (общий размер массива)

print('x3 ndim:', x3.ndim)
print('x3 shape:', x3.shape)
print('x3 size:', x3.size)

x3 ndim: 3
x3 shape: (3, 4, 5)
x3 size: 60


In [23]:
# Еще один полезный атрибут - dtype, тип данных массива

print('dtype', x3.dtype)

dtype int32


In [24]:
# itemsize - выводит размер в байтах каждого элемента
# nbytes - выводит полный размер массива в байтах

print('itemsize:', x3.itemsize, 'bytes')
print('nbytes:', x3.nbytes, 'bytes')

itemsize: 4 bytes
nbytes: 240 bytes


In [25]:
print(x1)

# Обращение по индексу к элементу одномерного массива происходит так же как в списках:
print('x1[0] =', x1[0])

# Для индексации с конца массива можно использовать отрицательные индексы:
print('x1[-1] =', x1[-1])

[5 0 3 3 7 9]
x1[0] = 5
x1[-1] = 9


In [26]:
# Обращаться к элементам в многомерном массиве можно с помощью разделенных запятыми кортежей индексов:

print(x2)

[[3 5 2 4]
 [7 6 8 8]
 [1 6 7 7]]


In [27]:
x2[0, 0]

3

In [28]:
# По индексу можно изменять значения в массиве:
x2[0, 0] = 7
print(x2)

[[7 5 2 4]
 [7 6 8 8]
 [1 6 7 7]]


In [29]:
# Так же необходимо помнить что массив типизирован и если попытаться вставить значение другого типа,
# оно будет неявно приведено к нужному типу. ВНИМАНИЕ!

x2[0, 0] = 3.14
print(x2)

[[3 5 2 4]
 [7 6 8 8]
 [1 6 7 7]]


In [30]:
x2[0, 0] = 12 # Вернем прежнее значение

In [31]:
# Массив поддерживает доступ к подмассивам с помощью срезов:
# x[начало, конец, шаг]

# Одномерные подмассивы
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [32]:
x[:5] # первые пять элементов

array([0, 1, 2, 3, 4])

In [33]:
x[5:] # элементы после индекса = 5

array([5, 6, 7, 8, 9])

In [34]:
x[4:7] # подмассив из середины

array([4, 5, 6])

In [35]:
x[::2] # каждый 2-ой элемент

array([0, 2, 4, 6, 8])

In [36]:
x[1::2] # каждый 2-ой элемент, начиная с индекса 1

array([1, 3, 5, 7, 9])

In [37]:
# К небольшой путанице может привести отрицательное значение параметра шаг. 
# В этом случае значения по умолчанию для начало и конец меняются местами.
# Это удобный способ "перевернуть" массив

x[::-1] # все элементы в обратном порядке

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [38]:
x[5::-2] # каждый второй элемент в обратном порядке, начиная с индекса 5

array([5, 3, 1])

**Многомерные подмассивы**

In [39]:
x2

array([[12,  5,  2,  4],
       [ 7,  6,  8,  8],
       [ 1,  6,  7,  7]])

In [40]:
x2[:2, :3] # две строки, три столбца

array([[12,  5,  2],
       [ 7,  6,  8]])

In [41]:
x2[:3, ::2] # все строки, каждый второй столбец

array([[12,  2],
       [ 7,  8],
       [ 1,  7]])

In [42]:
# Измерения подмассивов так же можно "переворачивать":
x2[::-1, ::-1]

array([[ 7,  7,  6,  1],
       [ 8,  8,  6,  7],
       [ 4,  2,  5, 12]])

Доступ к строкам и столбцам массива

In [43]:
print(x2[:, 0]) # первый столбец массива x2

[12  7  1]


In [44]:
print(x2[0, :]) # первая строка массива

[12  5  2  4]


In [45]:
# В случае обращения к строке пустой срез можно опустить ради более лаконичного синтаксиса:
print(x2[0]) # эквивалентно x2[0, :]

[12  5  2  4]


Срезы массивов возвращают *представления* (views), а не *копии* (copies) данных массива. Этим срезы массивов библиотеки numpy отличаются от срезов списков языка Python (в списках срезы являются копиями)

In [46]:
# Рассмотрим наш двумерный массив

print(x2)

[[12  5  2  4]
 [ 7  6  8  8]
 [ 1  6  7  7]]


In [48]:
# Извлечем из него двумерный подмассив 2 х 2

x2_sub = x2[:2, :2]
print(x2_sub)

[[12  5]
 [ 7  6]]


In [51]:
# Теперь, если мы изменим этот подмассив, увидим, что исходный массив так же поменялся.

# старое значение x2_sub[0, 0] = 12
x2_sub[0, 0] = 99
print(x2)

[[99  5  2  4]
 [ 7  6  8  8]
 [ 1  6  7  7]]


Иногда бывает удобно явным образом скопировать данные из массива или подмассива. Это можно сделать с помощью метода **.copy()**

In [52]:
x2_sub_copy = x2[:2, :2].copy()
print(x2_sub_copy)

[[99  5]
 [ 7  6]]


In [53]:
# Если мы теперь поменяем этот подмассив, исходный массив останется неизменным:
x2_sub_copy[0, 0] = 42
print(x2_sub_copy)

[[42  5]
 [ 7  6]]


In [54]:
print(x2)

[[99  5  2  4]
 [ 7  6  8  8]
 [ 1  6  7  7]]


**Изменение формы массивов**

Еще одна операция - изменение формы массивов методом **.reshape()**. Например, если требуется поместить числа от 1 до 9 в таблицу 3 х 3, сделать это можно следующим образом:

In [55]:
grid = np.arange(1, 10).reshape((3, 3))
print(grid)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [63]:
# Преобразование одномерного массива в двумерную матрицу-строку 
# или матрицу-столбец.

x = np.array([1, 2, 3])
x

array([1, 2, 3])

In [64]:
# Преобразование в вектор-строку с помощью reshape
x.reshape((1, 3))

array([[1, 2, 3]])

In [65]:
# Преобразование в вектор-строку посредством newaxis (рекомендуемый метод)
x[np.newaxis, :]

array([[1, 2, 3]])

In [67]:
# Преобразование в вектор-столбец с помощью reshape
x.reshape((3, 1))

array([[1],
       [2],
       [3]])

In [68]:
# Преобразование в вектор-столбец посредством newaxis
x[:, np.newaxis]

array([[1],
       [2],
       [3]])

**Слияние и разбиение массивов**

Все предыдущие операции работали с одним массивом. Но можно объединять несколько массивов в один и наоборот, разбить единый массив на несколько подмассивов. 

Слияние, или объединение, двух массивов в библиотеке NumPy выполняется в основном с методов:
- **np.concatenate**
- **np.vstack**
- **np.hstack**

In [44]:
# Метод np.concatenate принимает на вход кортеж или список массивов в качестве первого аргумента:

x = np.arange(1, 4)
y = np.arange(3, 0, -1)
np.concatenate([x, y])

array([1, 2, 3, 3, 2, 1])

In [47]:
# Можно объединять более двух массивов одновременно:

z = [99, 99, 99]
np.concatenate([x, y, z])

array([ 1,  2,  3,  3,  2,  1, 99, 99, 99])

In [50]:
# Для объединения двумерных массивов можно также использовать np.concatenate
grid = np.array([[1, 2, 3],
                [4, 5, 6]])
grid

array([[1, 2, 3],
       [4, 5, 6]])

In [51]:
# Слияние по первой оси координат
np.concatenate([grid, grid])

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [52]:
# Слияние по второй оси координат (с индексом 0)
np.concatenate([grid, grid], axis=1)

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

In [57]:
# По умолчанию параметр axis = 0
np.concatenate([grid, grid], axis=0)

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

Для работы с массивами с различающимися измерениями удобнее и понятнее использовать функции np.vstack (вертикальное объединение) и np.hstack (горизонтальное объединение)

In [58]:
x = np.arange(1, 4)
grid = np.array([[9, 8, 7],
                [6, 5, 4]])

In [59]:
# Объединяет массивы по вертикали
np.vstack([x, grid])

array([[1, 2, 3],
       [9, 8, 7],
       [6, 5, 4]])

In [61]:
# Объединяет массивы по горизонтали
y = np.array([99, 99]).reshape((2, 1))
np.hstack([grid, y])

array([[ 9,  8,  7, 99],
       [ 6,  5,  4, 99]])

**Разбиение массивов**

Противоположностью слияния является разбиение, выполняемое с помощью функций:
- **np.split**
- **np.hsplit**
- **np.vsplit**

Каждой из них необходимо передавать список индексов, задающих точки раздела.

In [62]:
x = [1, 2, 3, 99, 99, 3, 2, 1]
x1, x2, x3 = np.split(x, [3, 5])
print(x1, x2, x3)

[1 2 3] [99 99] [3 2 1]


Обратим внимание, что N точек раздела означают N+1 подмассив. Соответствующие функции np.hsplit и vsplit действуют аналогично

In [63]:
grid = np.arange(16).reshape((4, 4))
grid

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [66]:
upper, lower = np.vsplit(grid, [2])
print(upper)
print('\n', lower)

[[0 1 2 3]
 [4 5 6 7]]

 [[ 8  9 10 11]
 [12 13 14 15]]


In [68]:
left, right = np.hsplit(grid, [2])
print(left)
print('\n', right)

[[ 0  1]
 [ 4  5]
 [ 8  9]
 [12 13]]

 [[ 2  3]
 [ 6  7]
 [10 11]
 [14 15]]


## Введение в универсальные функции

Рассмотрим следудующий пример: Пусть у нас имеется массив значений и необходимо вычислить обратную величину каждого из них. Очевидное решение могло бы выглядеть следующим образом:

In [69]:
import numpy as np
np.random.seed(0)

def compute_reciprocals(values):
    output = np.empty(len(values))
    for i in range(len(values)):
        output[i] = 1.0 / values[i]
    return output

values = np.random.randint(1, 10, size=5)
compute_reciprocals(values)

array([0.16666667, 1.        , 0.25      , 0.25      , 0.125     ])

Такая реализация, вероятно, кажется вполне естественной. Однако оценив время выполнения этого кода для большого объема данных, мы обнаружим, что данная операция выполняется крайне медленно. Оценим это время с помощью "магической" функции %timeit

In [72]:
big_array = np.random.randint(1, 100, size=1000000)

%timeit compute_reciprocals(big_array)

1.53 s ± 7.21 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


Видим, что время выполнения милиона операций составляет почти 2 секунды, что абсурдно много. Связано это с тем, что из-за динамической типизации, при выполнении каждой операции каждый раз Python сначала проверяет тип объекта и выполняет динамический поиск подходящей для этого типа операции.

Библиотека NumPy предоставляет для многих типов операций удобный интерфейс для компилируемой процедуры со статической типизацией. Он известен под названием *векторизованной* операции. Для этого достаточно просто выполнить операцию с массивом, которая затем будет применена для каждого из его элементов. Векторизованный подход спроектирован так, чтобы переносить цикл в скомпилированный слой, лежащий в основе библиотеки NumPy, что обеспечивает гораздо более высокую производительность.

In [74]:
# Замерим время выполнения векторизованной операции.

%timeit 1 / big_array

3.29 ms ± 37.1 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [75]:
1.53 / 0.00329

465.04559270516717

Видим, что векторизованная операция выполняется почти в 500 раз быстрее

In [77]:
# Так же можно выполнять операции над двумя массивами
np.arange(5) / np.arange(1, 6)

array([0.        , 0.5       , 0.66666667, 0.75      , 0.8       ])

In [80]:
# Операции с универсальными функциями также могут работать и с многомерными массивами
x = np.arange(9).reshape((3, 3))
2 ** x

array([[  1,   2,   4],
       [  8,  16,  32],
       [ 64, 128, 256]], dtype=int32)

Вычисления с применением векторизации посредством универсальных функций практически всегда более эффективны чем их эквиваленты, реализованные с помощью циклов Python, особенно при росте размера массивов. Столкнувшись с подобным циклом в сценарии на языке Python, следует обдумать, не стоит ли заменить его векторизованным выражением.