In [2]:
help(len)

Help on built-in function len in module builtins:

len(obj, /)
    Return the number of items in a container.



In [3]:
len?

In [4]:
import numpy as np
np.array?

In [5]:
def square(a):
    """Return square a"""
    return a ** 2

In [6]:
square?

In [7]:
np?

In [8]:
np.doc?

Object `np.doc` not found.


In [9]:
np.array([1, 2, 3, 4], dtype='float32')

array([1., 2., 3., 4.], dtype=float32)

In [10]:
# Создаем массив целых чисел длины 10, заполненной нулями.
np.zeros(10, dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [11]:
np.zeros((2, 2), dtype=int)

array([[0, 0],
       [0, 0]])

In [12]:
# Создаем массив размером 3 х 5 значений с плавающей точкой, заполненный единицами
np.ones((3, 5), dtype=float)

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [13]:
# Создаем массив размером 2 х 6 заполненный р
np.full((2, 4), 3.14)

array([[3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14]])

In [14]:
# Создаем массив заполненный линейной последовательностью, начинающийся с 0 и заканчивающийся 20 с шагом 2
# (Аналогично встроенной функции range())
np.arange(0, 20, 2, dtype=float)

array([ 0.,  2.,  4.,  6.,  8., 10., 12., 14., 16., 18.])

In [15]:
np.arange?

In [16]:
# Создаем массив из 5 значений, равномерно располагающихся между 0 и 1
np.linspace(0, 1, 5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [17]:
# Создаем массив размером 3 х 3 равномерно распределенных случайных значений от 0 до 1
np.random.random((3, 3))

array([[0.18107346, 0.68819795, 0.07596222],
       [0.66408276, 0.39494733, 0.53847798],
       [0.40807918, 0.33118531, 0.63252741]])

In [18]:
# Создаем массив размером 4 х 4 нормально распределенных случайных значений,
# с медианой 0 и стандартным отклонением 1
np.random.normal(0, 1, (4, 4))

array([[ 1.23823947,  1.09666801, -0.25369164,  0.07811459],
       [-0.69838083, -0.81113559, -0.34448612, -0.68706238],
       [ 0.95960922,  0.69307064,  0.53770355,  0.05470899],
       [-0.99399678, -0.53675251, -2.29440849,  0.55308451]])

In [19]:
# Создаем массив размером 3 х 3 случайных целых чисел в промежутке [0, 10)
np.random.randint(0, 10, (3, 3))

array([[2, 9, 3],
       [6, 1, 9],
       [4, 8, 2]])

In [20]:
# Создаем единичную матрицу 3 х 3
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [21]:
# Можно принудительно привести к типу С
np.zeros(10, dtype=np.int16)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int16)

In [22]:
# Воспользуемся генератором случайных чисел библиотеки numpy, задав для него начальное значение,
# чтобы гарантировать генерацию одних и тех же массивов при каждом выполнении кода:

np.random.seed(0) # начальное значение для целей воспроизводимости

x1 = np.random.randint(10, size=6) # одномерный массив
x2 = np.random.randint(10, size=(3, 4)) # двумерный массив
x3 = np.random.randint(10, size=(3, 4, 5)) # трехмерный массив

In [23]:
# У каждого из массивов есть атрибуты ndim (размерность), shape (размер каждого измерения) и size (общий размер массива)

print('x3 ndim:', x3.ndim)
print('x3 shape:', x3.shape)
print('x3 size:', x3.size)

x3 ndim: 3
x3 shape: (3, 4, 5)
x3 size: 60


In [24]:
# Еще один полезный атрибут - dtype, тип данных массива

print('dtype', x3.dtype)

dtype int32


In [25]:
# itemsize - выводит размер в байтах каждого элемента
# nbytes - выводит полный размер массива в байтах

print('itemsize:', x3.itemsize, 'bytes')
print('nbytes:', x3.nbytes, 'bytes')

itemsize: 4 bytes
nbytes: 240 bytes


In [27]:
print(x1)

# Обращение по индексу к элементу одномерного массива происходит так же как в списках:
print('x1[0] =', x1[0])

# Для индексации с конца массива можно использовать отрицательные индексы:
print('x1[-1] =', x1[-1])

[5 0 3 3 7 9]
x1[0] = 5
x1[-1] = 9


In [29]:
# Обращаться к элементам в многомерном массиве можно с помощью разделенных запятыми кортежей индексов:

print(x2)

[[3 5 2 4]
 [7 6 8 8]
 [1 6 7 7]]


In [30]:
x2[0, 0]

3

In [31]:
# По индексу можно изменять значения в массиве:
x2[0, 0] = 7
print(x2)

[[7 5 2 4]
 [7 6 8 8]
 [1 6 7 7]]


In [32]:
# Так же необходимо помнить что массив типизирован и если попытаться вставить значение другого типа,
# оно будет неявно приведено к нужному типу. ВНИМАНИЕ!

x2[0, 0] = 3.14
print(x2)

[[3 5 2 4]
 [7 6 8 8]
 [1 6 7 7]]


In [34]:
# Массив поддерживает доступ к подмассивам с помощью срезов:
# x[начало, конец, шаг]

# Одномерные подмассивы
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [35]:
x[:5] # первые пять элементов

array([0, 1, 2, 3, 4])

In [36]:
x[5:] # элементы после индекса = 5

array([5, 6, 7, 8, 9])

In [37]:
x[4:7] # подмассив из середины

array([4, 5, 6])

In [38]:
x[::2] # каждый 2-ой элемент

array([0, 2, 4, 6, 8])

In [39]:
x[1::2] # каждый 2-ой элемент, начиная с индекса 1

array([1, 3, 5, 7, 9])

In [40]:
# К небольшой путанице может привести отрицательное значение параметра шаг. 
# В этом случае значения по умолчанию для начало и конец меняются местами.
# Это удобный способ "перевернуть" массив

x[::-1] # все элементы в обратном порядке

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [41]:
x[5::-2] # каждый второй элемент в обратном порядке, начиная с индекса 5

array([5, 3, 1])