In [1]:
help(len)

Help on built-in function len in module builtins:

len(obj, /)
    Return the number of items in a container.



In [2]:
len?

In [3]:
import numpy as np
np.array?

In [4]:
def square(a):
    """Return square a"""
    return a ** 2

In [5]:
square?

In [6]:
np?

In [7]:
np.doc?

Object `np.doc` not found.


In [8]:
np.array([1, 2, 3, 4], dtype='float32')

array([1., 2., 3., 4.], dtype=float32)

In [9]:
# Создаем массив целых чисел длины 10, заполненной нулями.
np.zeros(10, dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [11]:
np.zeros((2, 2), dtype=int)

array([[0, 0],
       [0, 0]])

In [12]:
# Создаем массив размером 3 х 5 значений с плавающей точкой, заполненный единицами
np.ones((3, 5), dtype=float)

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [13]:
# Создаем массив размером 2 х 6 заполненный р
np.full((2, 4), 3.14)

array([[3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14]])

In [15]:
# Создаем массив заполненный линейной последовательностью, начинающийся с 0 и заканчивающийся 20 с шагом 2
# (Аналогично встроенной функции range())
np.arange(0, 20, 2, dtype=float)

array([ 0.,  2.,  4.,  6.,  8., 10., 12., 14., 16., 18.])

In [16]:
np.arange?

In [19]:
# Создаем массив из 5 значений, равномерно располагающихся между 0 и 1
np.linspace(0, 1, 5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [21]:
# Создаем массив размером 3 х 3 равномерно распределенных случайных значений от 0 до 1
np.random.random((3, 3))

array([[0.60350781, 0.07923143, 0.3550312 ],
       [0.86795182, 0.64806918, 0.85639069],
       [0.23579977, 0.33026177, 0.10321948]])

In [22]:
# Создаем массив размером 4 х 4 нормально распределенных случайных значений,
# с медианой 0 и стандартным отклонением 1
np.random.normal(0, 1, (4, 4))

array([[-0.09761953, -1.24914813, -0.75304838,  0.37154303],
       [ 0.15805571,  0.40236616,  1.49903022,  1.19697892],
       [ 2.59202028,  0.74044175, -0.83074248,  0.95296755],
       [ 0.90216437,  0.35975522,  1.48791008, -0.03773857]])

In [23]:
# Создаем массив размером 3 х 3 случайных целых чисел в промежутке [0, 10)
np.random.randint(0, 10, (3, 3))

array([[3, 9, 5],
       [5, 5, 9],
       [3, 8, 5]])

In [26]:
# Создаем единичную матрицу 3 х 3
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])